name: Gjør noe
description: lorem
title: Add a title for your issue, try to keep it shorter than ~100 characters
labels: [triage]
assignees: self
body:
  - type: input
    id: litt_tekst
    attributes:
      label: input_type
      description: "type: input"
      placeholder: "Skriv noe"
    validations:
      required: true
  - type: textarea
    id: mye_tekst
    attributes:
      label: textarea_type
      description: "type: text area"
      placeholder: |
        Skriv før du

        tenker
    validations:
      required: true
