name: Gjør noe
description: lorem
title: Add a title for your issue, try to keep it shorter than ~100 characters
labels: [triage]
assignees: self
body:
  - type: input
    id: litt tekst
    attributes:
      label: input type
      description: "??"
      placeholder: "Skriv noe"
    validations:
      required: true
  - type: textarea
    id: mye tekst
    attributes:
      label: textarea type
      description:
      placeholder: |
        Skriv før du

        tenker
    validations:
      required: true
